In [9]:
a=12;
b=2;
c=a+b;
print(c)
print("Address of a:", id(a))// id : to see the adress of "ca"
print("Address of b:", id(b))
print("Address of c:", id(c))

14
Address of a: 140707202411288
Address of b: 140707202410968
Address of c: 140707202411352


In [ ]:
##Numpy :numerical python which is basic package for data science
# ndarray is the core of the "numpy pacakge"
#ndarray it procesess n-dim arrays of homogenious data types 

In [15]:
import numpy as np #"as" alias 
np.__version__

'1.26.4'

In [33]:
import numpy as np
arr1=np.array([1,2,3,4])#array
arr2=np.array([23,34,56])
print(arr1,arr2)
type(arr1)
type(arr2)
print("Address of arr1,arr2:", id(arr1),id(arr2))

[1 2 3 4] [23 34 56]
Address of arr1,arr2: 2213256750608 2213286016464


In [37]:
arr3=arr1
print(arr3)
print("Address of arr3:", id(arr3))

[1 2 3 4]
Address of arr3: 2213256750608


In [41]:
arr4=np.copy(arr1)
print(arr4)
print("Address of arr4:", id(arr4))#copy will give you the different adress 

[1 2 3 4]
Address of arr4: 2213229646192


In [49]:
a=np.array((1,2,3,4,5))#tuple and which is immutable(where u cant add or remove the elements  )
print(a)
print("Address of a:", id(a))
b=type(a)#type and class is different
print(b)
type((1,2,3,4,5))

[1 2 3 4 5]
Address of a: 2213256755408
<class 'numpy.ndarray'>


tuple

In [51]:
x=np.array({'one':2,'two':3})
y=type({'one':2,'two':3})
print(x,y)
print("Address of x:", id(x))
type(x)

{'one': 2, 'two': 3} <class 'dict'>
Address of x: 2213256755312


numpy.ndarray

In [53]:
{1,2,3,4,555,55,555}#set which will remove the duplicates automatically
#set is a built-in, unordered, mutable collection of unique elements.

{1, 2, 3, 4, 55, 555}

In [55]:
type({1,2,3,4,555,55,555})

set

In [85]:
ar1=np.array([1,2,3,5])
#ar1.append(6) #in np.array u cant use append function 
print(ar1)
print(ar1+5)


[1 2 3 5]
[ 6  7  8 10]


In [89]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
[i for i  in np.arange(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(5,20,5)

array([ 5, 10, 15])

In [109]:
k=np.arange(7,77,7) #(a,b,c) a :starts from ,b:stops , c:steps 
print(k)
print(len(k))
print(k.size)

[ 7 14 21 28 35 42 49 56 63 70]
10
10


In [115]:
i=np.array([11,2.5,True]) #here it will convert it into one data type +
type(i[2])
type(i[1])

numpy.float64

In [130]:
np.array(['apple','banana','aybtyui']) #here dtype='<U7' represents the it can store upto 7 characters 


array(['apple', 'banana', 'aybtyui'], dtype='<U7')

In [132]:
j=np.array(['apple','banana','aybtyui']) 
print(j)
type(j[0])

['apple' 'banana' 'aybtyui']


numpy.str_

In [134]:
np.linspace(1,10,5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [138]:
np.linspace(-10,10,25)

array([-10.        ,  -9.16666667,  -8.33333333,  -7.5       ,
        -6.66666667,  -5.83333333,  -5.        ,  -4.16666667,
        -3.33333333,  -2.5       ,  -1.66666667,  -0.83333333,
         0.        ,   0.83333333,   1.66666667,   2.5       ,
         3.33333333,   4.16666667,   5.        ,   5.83333333,
         6.66666667,   7.5       ,   8.33333333,   9.16666667,
        10.        ])

In [140]:
#This creates a NumPy array of size 5, filled with zeros.
#The default data type is float
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [142]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [156]:
d=np.array([[2,3],[7,9],[3,4]])
print(d)
d.size

[[2 3]
 [7 9]
 [3 4]]


6

In [160]:
print(d.T) #to print the transpose of the matrix 

[[2 7 3]
 [3 9 4]]


In [182]:
j=np.array([[[2,3],[7,9],[3,4]],[[4,5],[6,7],[6,8]]])
j.ndim #says the dimension 
print(j[0][1])#to print the element

[7 9]


In [21]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=a.size
print(b)
c=a.shape
print(c)
a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


2

In [41]:
a2=np.arange(1,16)#it will create single dimensional array 
print(a2)
a2.reshape((3,5)) #for reshape give the tuple parenthesis 
a2.reshape((5,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [55]:
data=np.random.randn(4,5) #4 rows and 5 columns 
print(data) #it is going to generate the reandom number from the std cure, guassian curve 

[[-1.34249229  0.15796111 -1.3266469   1.03151888 -0.56362222]
 [-0.63222244  0.36919765  0.32981847  0.50525391  0.70010262]
 [ 0.16283809 -0.47055841 -0.79130076  1.4584756   0.5611093 ]
 [-1.11799482 -1.37990769  0.69194629  0.53687816 -0.52618963]]


In [57]:
np.mean(data)

-0.08229175523543697

In [65]:
data3=np.random.randn(100,100)
print(data3)
np.mean(data3)

[[ 1.75765184 -1.62663661  1.1082155  ...  0.13059447  2.26532138
  -0.13733375]
 [ 0.26532514  1.05772003  0.30080683 ... -0.99268802  0.36444057
  -0.64404046]
 [ 0.56267543  0.23425538 -2.24555724 ...  0.45237577 -0.22137712
  -0.54794561]
 ...
 [-1.30851738 -0.89161899 -0.99659304 ...  1.73834473 -1.157187
  -1.75308683]
 [ 0.21365261  1.01237397  0.0985441  ...  1.48437977  2.20429506
   0.66169287]
 [-2.64459474 -1.83657226 -0.62137837 ...  1.32128492 -0.29411377
   1.16999906]]


-0.0005229778486264273

In [67]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [80]:
list(range(1000000))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [71]:
%time for i in range(1000):np.arange(1000000)*2

CPU times: total: 2.16 s
Wall time: 2.21 s


In [ ]:
%time for i in range(1000):list(range(1000000))*2
 

In [107]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.append(a,[[4,5,6],[6,7,8]],axis=0)#axis=0 it adds vertically
print(b)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]


In [109]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.append(a,[[4,5,6],[6,7,8]],axis=1)#axis=1 it adds horizantally
print(b)

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


In [113]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.delete(a,0)
print(b)

[2 3 3 4 5]


In [121]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.delete(a,0,axis=0)
print(b)

[[3 4 5]]


In [123]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.delete(a,0,axis=1)
print(b)

[[2 3]
 [4 5]]


In [125]:
a=[1,2,3,4,5]
b=[3,4,5,7]
a+b #here it is addeed th elements 

[1, 2, 3, 4, 5, 3, 4, 5, 7]

In [131]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,7,6])
a+b

array([ 4,  6,  8, 11, 11])

In [133]:
a=[1,2,3]
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [135]:
b=np.array([1,2,3])
3*b

array([3, 6, 9])

In [137]:
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [139]:
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [153]:
#i=np.array([[1,2,3,4],[2,3,4,5]])
i=np.arange(9)
b=i.reshape((3,3))
e=np.tile(b,2)
print(i)
print(b)
print(e)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


In [173]:
arr1=np.array([1,2,3,4])
arr1**2
print(arr1)
arr2=np.array([1,2,3,4])
arr1 / (arr2**2)

[1 2 3 4]


array([1.        , 0.5       , 0.33333333, 0.25      ])

In [175]:
arr2


array([1, 2, 3, 4])

In [177]:
arr2>10

array([False, False, False, False])

In [179]:
 x=np.array([0,1,2,3,4])
x**3

array([ 0,  1,  8, 27, 64], dtype=int32)

In [181]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [183]:
x_mean=x.mean()
x-x_mean

array([-2., -1.,  0.,  1.,  2.])

In [185]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [187]:
x=np.arange(1,11)

In [189]:
x.sum()

55

In [191]:
x.mean()

5.5

In [193]:
(x-x_mean)**2

array([ 1.,  0.,  1.,  4.,  9., 16., 25., 36., 49., 64.])

In [195]:
dev=(x-x_mean)**2

In [197]:
dev.sum()

205.0

In [199]:
dev.sum() /x.size

20.5

In [201]:
x.var()

8.25

In [203]:
np.sqrt(x.var())

2.8722813232690143

In [205]:
dev.sum() / x.size

20.5

In [207]:
x.std()

2.8722813232690143

In [209]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [217]:
x=np.arange(1,7)
x
x.reshape(2,3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [219]:
x.reshape(2,-1)


array([[1, 2, 3],
       [4, 5, 6]])

In [221]:
x.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [223]:
x=x.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [227]:
x.mean(axis=1)

array([2., 5.])

In [229]:
np.random.seed(123)

In [243]:
a=np.random.randint(1,10,size=100)
a

array([3, 9, 6, 1, 4, 4, 4, 2, 8, 7, 4, 2, 8, 3, 7, 6, 9, 5, 8, 9, 6, 3,
       5, 4, 4, 2, 8, 9, 6, 8, 8, 8, 6, 1, 1, 9, 2, 1, 5, 6, 5, 6, 1, 8,
       2, 3, 3, 8, 8, 4, 7, 2, 9, 5, 2, 7, 6, 1, 4, 2, 4, 8, 8, 8, 6, 4,
       7, 4, 6, 2, 6, 2, 4, 2, 6, 7, 2, 6, 1, 8, 1, 4, 1, 7, 3, 8, 6, 2,
       1, 1, 3, 7, 6, 2, 6, 4, 7, 5, 8, 2])

In [245]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [247]:
np.median(a)

5.0

In [249]:
np.var(a)

6.4379

In [251]:
np.mean(a)

4.89

In [253]:
np.round(np.var(a),2)

6.44

In [255]:
np.round(np.mean(a),2)

4.89

In [257]:
np.round(np.std(a),2)

2.54

In [259]:
np.max(a)

9

In [261]:
np.min(a)

1

In [263]:
a=np.array([2,-3,4,5,7,0,1,-1])
a

array([ 2, -3,  4,  5,  7,  0,  1, -1])

In [265]:
a.argmax()

4

In [267]:
a.argmin()

1

In [271]:
A=np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [273]:
B=np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [275]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [277]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [287]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [289]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [291]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [293]:
np.linalg.det(A)

-2.0

In [297]:
i=np.array([0,1,2,3])
j=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
i[0]

0

In [299]:
j[0]

array([0, 1, 2, 3])

In [301]:
j[0][1]

1

In [303]:
i[2]=7

In [305]:
i

array([0, 1, 7, 3])

In [307]:
j[0]=[1,2,3,4]

In [309]:
j

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [327]:
i[0:-2]

array([0, 1])

In [317]:
i

array([0, 1, 7, 3])

In [329]:
a2=np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [331]:
a2[0,2]

30

In [335]:
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [337]:
a2[[0,2],[0,1]]

array([10, 80])

In [339]:
b1=np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [341]:
b1[:3]

array([ 0, 10, 20])

In [343]:
b1[2:]

array([20, 30, 40, 50])

In [347]:
a2[:2,1:]

array([[20, 30],
       [50, 60]])

In [355]:
arr2d=np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [357]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [359]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [361]:
arr2d[1,:2]

array([4, 5])

In [363]:
arr2d[:2,2]

array([3, 6])

In [365]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [381]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [383]:
arr2d[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [385]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [391]:
arr2d[2]


array([7, 8, 9])

In [393]:
arr2d[2,:]
arr2d[2:,:]

array([[7, 8, 9]])

In [395]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [397]:
arr2d[1,:2]

array([4, 5])

In [399]:
arr2d[1:2,:2]

array([[4, 5]])

In [9]:
sales_per_sec = 350
s_min = sales_per_sec * 60
s_hour = sales_per_min * 60
s_day = sales_per_hour * 24
s_month = sales_per_day * 30   
s_year = sales_per_day * 365     

print("Sales per minute:",s_min)
print("sales per hour:",s_hour)
print("sales per day:",s_day)
print("sales per day:",s_year)
print("sales per day:",s_month)


Sales per minute: 21000
sales per hour: 1260000
sales per day: 30240000
sales per day: 11037600000
sales per day: 907200000


In [1]:
# STEP 1: Setup Kaggle API
import os
import shutil

# Move kaggle.json to ~/.kaggle
shutil.copy("kaggle.json", os.path.expanduser("~/.kaggle/kaggle.json"))
os.chmod(os.path.expanduser("~/.kaggle/kaggle.json"), 0o600)

# STEP 2: Install Kaggle CLI (if needed)
!pip install -q kaggle

# STEP 3: Download Uber dataset
!kaggle datasets download -d yashdevladdha/uber-ride-analytics-dashboard

# STEP 4: Unzip dataset
import zipfile

with zipfile.ZipFile("uber-ride-analytics-dashboard.zip", 'r') as zip_ref:
    zip_ref.extractall("uber_data")

# STEP 5: Load dataset
import pandas as pd

df = pd.read_csv("uber_data/Uber Request Data.csv")
print("Shape:", df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'kaggle.json'